@startuml
title Trafikkmengde - Objekttyper

skinparam backgroundColor #F5F5F5
skinparam shadowing false
skinparam RoundCorner 6
skinparam ArrowColor #6C8198
skinparam class {
  BackgroundColor #FBF2E8
  BorderColor #9C8578
  FontColor #2D201A
  HeaderBackgroundColor #EFE1D6
  HeaderFontColor #2D201A
  AttributeIconSize 0
}
skinparam note {
  BackgroundColor #FFFFFF
  BorderColor #6C8198
  FontColor #2D201A
}
skinparam stereotypeCBackgroundColor #EAD9CE
skinparam stereotypeCBorderColor #9C8578
skinparam stereotypeCFontColor #2D201A

package "Objekttyper" {

  class Trafikkmengde <<featureType>> {
    + senterlinje [1] : Kurve
    + ådtTotal [1] : Real
    + ådtAndelLangeKjøretøy [1] : Real
    + årGjelderFor [1] : Real
    + grunnlagForÅDT [0..1] : GrunnlagForÅDT
    + ådtStart [0..1] : Real
    + ådtSlutt [0..1] : Real
  }
}

  Veglenke <|-- Trafikkmengde

@enduml
